### ISSUE TITLE
[New azd-template] FastAPI on Azure Container Apps

### ISSUE THREAD

**Issue by pamelafox** [Azure/awesome-azd#113]
## New azd-template Submission
Fill in the sections below to populate a new gallery card for your template. **All fields are mandatory unless explicitly identified as optional**

## 1. Description

A simple JSON API using the Python FastAPI app framework, designed for deployment on Azure Container Apps. Includes auto-configuration of gunicorn with uvicorn worker count based on CPUs available.

## 2. Author Information
**Name:** Pamela Fox

**Link:** https://github.com/pamelafox

## 3. Template Repo

https://github.com/pamelafox/simple-fastapi-container

## 4. Link to PR where you made your repo `azd` compatible

Sorry, there wasn't a single PR. Please check infra folder, .github folder, .devcontainer folder.

## 5. Tags
**Standard:** Python, Bicep, FastAPI, Azure Container Apps

## 6. Architecture Diagram or Application Screenshot

Same architecture as Flask API sample:

https://raw.githubusercontent.com/pamelafox/simple-fastapi-container/main/readme_diagram.png

## 7. Related Issues (optional)
_Is this a template that was requested in a separate issue? If so, please tag the related issue here._
---

## Next Steps
Once submitted, the issue will be reviewed - we plan to do reviews on a rolling basis at regular intervals. The process will include verifying all information required for the template gallery is provided and the template works (i.e., successfully deploys to Azure with `azd up`). 
 * If we have questions or enhancements, we will add comments in issue thread (**issue stays open**)
 * If the contribution is approved, we'll update the gallery directly (**issue will then be closed**)

**Comment by v-xuto** [comment]
@pamelafox We have finished testing this template. We found an issue in README and filed the issue, please review and update.
Issue link: https://github.com/pamelafox/simple-fastapi-container/issues/7

**Comment by pamelafox** [comment]
Thanks, replied there!

**Comment by rajeshkamal5050** [comment]
@jongio kindly review, when you get a chance.

**Comment by jongio** [comment]
🚢

**Comment by rajeshkamal5050** [comment]
@pamelafox For adding template to https://azure.github.io/awesome-azd/ gallery. Do you want to create a PR and give it a try? So we can review/approve(@savannahostrowski @hemarina @rajeshkamal5050 @jongio)? 

We have some prior reference PR's for adding templates to the gallery.
- Leveraging existing tags - https://github.com/Azure/awesome-azd/pull/112
- Adding new tags - https://github.com/Azure/awesome-azd/pull/111
