### ISSUE TITLE
[New azd-template] Django on ACA with PostgreSQL and Keyvault

### ISSUE THREAD

**Issue by kjaymiller** [Azure/awesome-azd#118]
## New azd-template Submission
Fill in the sections below to populate a new gallery card for your template. **All fields are mandatory unless explicitly identified as optional**

## 1. Description
A Space Tourism appallication written with Django deployed via Azure Container Apps that uses Azure PostgreSQL Flexible Server and Key Vault secret management.

## 2. Author Information
**Name:** Microsoft Python Cloud Advocacy

**Link:** https://github.com/azure-samples

## 3. Template Repo
https://github.com/Azure-Samples/azure-django-postgres-aca

## 4. Link to PR where you made your repo `azd` compatible
Project was created with AZD in mind. Information is in Azure.yaml and the infra folder

## 5. Tags
**Standard:** _One or more tags representing the template. Look at the currently available tags on the [Gallery page](https://azure.github.io/awesome-azd/). Provide **at least 1 tag** for programming language used and **at least 1 tag for Azure services integrated**. Also tag the **IaC provider** (Bicep or Terraform)_
Python, PostgreSQL, bicep, azure container apps, 

**Additional:** _Don't see a relevant tag for your template? Suggest tags to be added and used for your template. These could be new languages, services, or application domains_.

## 6. Architecture Diagram or Application Screenshot

![readme_architecture](https://user-images.githubusercontent.com/8632637/228957554-13f84623-48a3-45c6-acc3-4b81566bc74f.png)

## 7. Related Issues (optional)
_Is this a template that was requested in a separate issue? If so, please tag the related issue here._
---

## Next Steps
Once submitted, the issue will be reviewed - we plan to do reviews on a rolling basis at regular intervals. The process will include verifying all information required for the template gallery is provided and the template works (i.e., successfully deploys to Azure with `azd up`). 
 * If we have questions or enhancements, we will add comments in issue thread (**issue stays open**)
 * If the contribution is approved, we'll update the gallery directly (**issue will then be closed**)

**Comment by rajeshkamal5050** [comment]
@v-xuto can you do validate the template and do a dry run of it?

**Comment by jongio** [comment]
nit: azure.yaml doesn't need provider if using bicep

🚢

**Comment by kjaymiller** [comment]
> @kjaymiller can you address the read me issue above?
> 
> @jongio kindly review, when you get a chance.

I have updated the readme with the requested changes

**Comment by kjaymiller** [comment]
cc @rajeshkamal5050 @savannahostrowski

**Comment by rajeshkamal5050** [comment]
Thanks @kjaymiller 

For adding your template to the https://azure.github.io/awesome-azd/ gallery. Do you want to give it a try? and we can review/approve(@savannahostrowski @hemarina @rajeshkamal5050 @jongio)? 

We have some prior reference PR's for the same.
- Leveraging existing tags - https://github.com/Azure/awesome-azd/pull/112
- Adding new tags - https://github.com/Azure/awesome-azd/pull/111

**Comment by kjaymiller** [comment]
https://github.com/Azure/awesome-azd/pull/127
