### ISSUE TITLE
[New azd-template] .NET File Manager

### ISSUE THREAD

**Issue by alexwolfmsft** [Azure/awesome-azd#130]
## New azd-template Submission
Fill in the sections below to populate a new gallery card for your template. **All fields are mandatory unless explicitly identified as optional**

## 1. Description
This simple starter azd template provides a basic file manager app. It deploys an ASP.NET Core web app to Azure App Service and creates an Azure Storage account with a blob container. It then connects the App Service to the Storage account using a connection string configuration setting. The app uses the Azure SDK to allow users to upload files to the storage account and view them as a list of links. It also supports GitHub actions as a CI/CD pipeline.

## 2. Author Information
**Name:** Alex Wolf

**Link:** https://github.com/alexwolfmsft

## 3. Template Repo
https://github.com/alexwolfmsft/azd-file-manager

## 4. Link to PR where you made your repo `azd` compatible
This was built from scratch for azd awesome.

## 5. Tags
**Standard:** _One or more tags representing the template. Look at the currently available tags on the [Gallery page]
.NET/C#, Azure App Service, Azure Blob Storage

## 6. Architecture Diagram or Application Screenshot
Not sure if this is necessary for a simple app.

## 7. Related Issues (optional)
NA
---
## Next Steps
Once submitted, the issue will be reviewed - we plan to do reviews on a rolling basis at regular intervals. The process will include verifying all information required for the template gallery is provided and the template works (i.e., successfully deploys to Azure with `azd up`). 
 * If we have questions or enhancements, we will add comments in issue thread (**issue stays open**)
 * If the contribution is approved, we'll update the gallery directly (**issue will then be closed**)

**Comment by rajeshkamal5050** [comment]
@v-xuto can you validate, test the template and update?

**Comment by v-xuto** [comment]
@alexwolfmsft Please add the ReadMe for this repo https://github.com/alexwolfmsft/azd-file-manager, so that we can test it.

**Comment by alexwolfmsft** [comment]
Hey @v-xuto  I have added a readme file to this project.

**Comment by v-xuto** [comment]
@rajeshkamal5050 Sure. We have finished testing this template. 
@alexwolfmsft We have finished testing this template, there is an issue https://github.com/alexwolfmsft/azd-file-manager/issues/1, please review.

**Comment by alexwolfmsft** [comment]
Hey @v-xuto I have updated the template to support application insights, which should have fixed this issue, thanks!

**Comment by v-xuto** [comment]
@alexwolfmsft This issue has been fixed. We've closed it.
@rajeshkamal5050 Now, there is no issue with this template.

**Comment by alexwolfmsft** [comment]
Hey @rajeshkamal5050  - any updates on this? Thanks!

**Comment by jongio** [comment]
Please add a devcontainer to the project.  You can find examples to use in our official templates.  Thanks

**Comment by alexwolfmsft** [comment]
Hey @jongio  I have added the devcontainer folder/assets like the other templates have.

**Comment by jongio** [comment]
More suggestions:

Steal the code in this readme to display the buttons.

Add text to readme on how to open in codespaces...


https://github.com/Azure-Samples/openai-plugin-fastapi

**Comment by alexwolfmsft** [comment]
@jongio I think this is all set

**Comment by jongio** [comment]
I got this:

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
AccountNameInvalid: stjongfilemanager1storage is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.

TraceID: 1caf6924e776b2b34fdc654c10c9be75


I recommend adding validation to the names to adhere to the naming conventions.
