### ISSUE TITLE
[New azd-template] Python (Flask) Web App with PostgreSQL

### ISSUE THREAD

**Issue by pamelafox** [Azure/awesome-azd#132]
## 1. Description

A Python Flask app on App Service with a PostgreSQL flexible server database. Database access is restricted to Azure IPs, and admin password is generated randomly.

## 2. Author Information

**Name:** Pamela Fox

**Link:** https://github.com/pamelafox

## 3. Template Repo

https://github.com/pamelafox/flask-db-quiz-example

## 4. Link to PR where you made your repo `azd` compatible

As usual, I don't have one PR. You can look through my checklist to see what I checked off as doing for this template: https://github.com/pamelafox/python-azd-template/issues/2

Notably:
* This template is not using as many security best practices as others, so I've made sure to call that out loudly in the README. I thought it might be helpful to have this infra available for those wanting the simplest approach.
* This template doesn't support `azd monitor`. That would complicate the sample more since Python apps require OpenCensus/OpenTelemetry for proper monitoring.

## 5. Tags
**Standard:** python, flask, bicep, azure app service, web apps, azure db for postgresql

## 6. Architecture Diagram or Application Screenshot

https://github.com/pamelafox/flask-db-quiz-example/raw/main/readme_diagram.png

## 7. Related Issues (optional)

N/A

---
## Next Steps
Once submitted, the issue will be reviewed - we plan to do reviews on a rolling basis at regular intervals. The process will include verifying all information required for the template gallery is provided and the template works (i.e., successfully deploys to Azure with `azd up`). 
 * If we have questions or enhancements, we will add comments in issue thread (**issue stays open**)
 * If the contribution is approved, we'll update the gallery directly (**issue will then be closed**)

**Comment by pamelafox** [comment]
@savannahostrowski Originally, this was going to use the same architecture as the recently added Django one, but then I went a step further and removed Key Vault, since you indicated a desire for simpler approaches. The Django template requires Key Vault since Django requires a non-changing SECRET_KEY, but Flask only requires SECRET_KEY when you use sessions, which this app doesn't, so that allowed me to remove the Key Vault dependency. Let me know what you think!

**Comment by savannahostrowski** [comment]
Oh very neat! Thanks for trying that out! Excited to see some templates with simpler IaC!

@rajeshkamal5050 Did you want this to go through manual testing or is this ready for PR?

**Comment by rajeshkamal5050** [comment]
@v-xuto can you validate and test this template?

**Comment by v-xuto** [comment]
@rajeshkamal5050 We've run this template without any issues.
