### ISSUE TITLE
[New azd-template] app-templates-java-openai-springapps

### ISSUE THREAD

**Issue by aarthiem** [Azure/awesome-azd#179]
AI Shopping Cart is a sample application that supercharges your shopping experience with the power of AI. It leverages Azure OpenAI and Azure Spring Apps to build a recommendation engine that is not only scalable, resilient, and secure, but also personalized to your needs. Taking advantage of Azure OpenAI, the application performs nutrition analysis on the items in your cart and generates the top 3 recipes using those ingredients. With Azure Developer CLI (azd), you’re just a few commands away from having this fully functional sample application up and running in Azure.
https://github.com/Azure-Samples/app-templates-java-openai-springapps

**Comment by gkulin** [comment]
thanks @aarthiem, I'm excited about this template! Could you please open a PR to contribute it? You can find our guide for how to do so [here](https://azure.github.io/awesome-azd/docs/intro#contribute-a-new-template)
