### ISSUE TITLE
[New azd-template] Azure Cosmos DB for NoSQL + Azure OpenAI + Azure Container Apps

### ISSUE THREAD

**Issue by seesharprun** [Azure/awesome-azd#267]
### 1. Description

This template provides an end-to-end example of an ASP.NET Blazor chat web application with data stored in Azure Cosmos DB for NoSQL and Azure OpenAI used for chat completion.

### 2. Author Information

- **Name**: Azure Cosmos DB Content Team
- **Link**: https://learn.microsoft.com/azure/cosmos-db/

### 3. Template Repo

<https://github.com/azure-samples/chat-csharp-cosmos-db-nosql-openai>

### 4. Link to PR where you made your repo `azd` compatible

Repo was built from the start with `azd` in mind.

### 5. Tags

- Bicep
- Azure Container Apps
- .NET/C#
- Artificial Intelligence
- Azure OpenAI
- ChatGPT
- New
- Azure Cosmos DB
- Microsoft Authored

### 6. Architecture Diagram or Application Screenshot

![Screenshot of the running web application.](https://raw.githubusercontent.com/Azure-Samples/chat-csharp-cosmos-db-nosql-openai/main/assets/screenshot.png)

### 7. Additional info

Here's the JSON I put together for the template:

```json
{
  "title": "ASP.NET Blazor chat application with Azure Cosmos DB for NoSQL, Azure Container Apps, and Azure OpenAI", 
  "description": "A sample sample chat application deployed to Azure Container Apps that answers questions from the user and tracks chat history across conversations. Chat sessions and history is stored in Azure Cosmos DB for NoSQL and chat completions are provided by Azure OpenAI.",
  "preview": "./templates/images/test.png",
  "website": "https://learn.microsoft.com/azure/cosmos-db/",
  "author": "Azure Cosmos DB Content Team",
  "source": "https://github.com/Azure-Samples/chat-csharp-cosmos-db-nosql-openai",
  "tags": ["bicep", "aca", "dotnetCsharp", "ai", "openai", "chatgpt", "new", "cosmosdb", "msft"]
}
```

The template also has a prebuilt devcontainer image that's compatible with GitHub Codespaces. This should reduce friction in using it.

**Comment by gkulin** [comment]
Thank you for your contribution, Sidney! Marina opened a pr for this template #271 and it was just merged! 

In the future, you can [open a pr for templates you'd like to contribute](https://azure.github.io/awesome-azd/docs/intro#contribute-a-new-template) to help us review your contribution even quicker!
