### ISSUE TITLE
Add Adobe support for usage

### ISSUE THREAD

**Issue by hemarina** [Azure/awesome-azd#278]
Currently we are not track any access data. We should add [Adobe](https://microsoft.sharepoint.com/teams/MarTechPortal/SitePages/website-tools/analytics-and-insights-LP.aspx?xsdata=MDV8MDJ8fGUyMGI5MzJlOWU1YTQyZjJhNGFmMDhkYzBjOGRhNzM3fDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2MzgzOTkwNDk3MTUxMzE1Njd8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPbVptTnpoaU9HUXhZV00yT0RSbVl6YzVNamhpWmpWbFlXTmpaREF3T0Rnd1FIUm9jbVZoWkM1Mk1pOXRaWE56WVdkbGN5OHhOekEwTXpBNE1UY3dPREkwfDc3OGZiYzg4OTg3MTQyZTdhNGFmMDhkYzBjOGRhNzM3fDA2NTc0YTc1NzM0YjRlYmM4YTI1MTFmNjE2ZGQ0NTVj&sdata=UjVsRDhLaWt5YUdPSXZYa0xXR3ZLck9PUU9mbVV5M0VGYUtxT2lxelZtRT0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cshboyer%40microsoft.com&OR=Teams-HL&CT=1704308987037&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzExMzAyNjIwMSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D) for usage.

**Comment by vhvb1989** [comment]
We will need to create a plugin like: https://github.com/gracefullight/docusaurus-plugins/blob/main/packages/docusaurus-plugin-microsoft-clarity/src/index.ts for docusaurus to produce the required script for Adobe Analytics :)
