### ISSUE TITLE
Publish `Microsoft Authored` templates to azure samples browser

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/awesome-azd#281]
Not all [Microsoft authored templates](https://azure.github.io/awesome-azd/?tags=msft) are onboarded to the [azure samples browser](https://learn.microsoft.com/en-us/samples/browse/?expanded=azure&languages=azdeveloper). The onboarding process https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main

Please refer to the issue and changes @weikanglim did for onboarding the TODO templates and do the same for all Microsoft Authored templates.
- https://github.com/Azure/azure-dev/issues/526
- https://github.com/Azure/azure-dev/pull/1556

cc @hemarina @gkulin @spboyer

**Comment by v-xuto** [comment]
@rajeshkamal5050  For publishing `Microsoft-authored` templates to Azure sample browser, we have created a PR, please review. If it's okay, we'll create PRs for the rest of templates.
- https://github.com/Azure-Samples/function-javascript-ai-openai-chatgpt/pull/7

**Comment by v-xuto** [comment]
> @v-xuto This PR LGTM. Feel free to create PRs for the rest of template while we are waiting function-javascript-ai-openai-chatgpt owner to merge the PR.

@hemarina Got it. We will create PRs for the rest of the templates.

**Comment by v-xuto** [comment]
@hemarina We have created 10 PRs so far, please review. 
- https://github.com/Azure-Samples/chat-csharp-cosmos-db-nosql-openai/pull/5
- https://github.com/Azure-Samples/function-python-ai-openai-chatgpt/pull/6
- https://github.com/Azure-Samples/function-python-ai-langchain/pull/6
- https://github.com/Azure-Samples/function-csharp-ai-textsummarize/pull/13
- https://github.com/Azure-Samples/function-python-ai-textsummarize/pull/5
- https://github.com/Azure-Samples/azure-sql-db-session-recommender/pull/20
- https://github.com/Azure-Samples/azd-deployment-environments/pull/2
- https://github.com/Azure-Samples/azure-search-openai-demo-csharp/pull/263
- https://github.com/Azure-Samples/azure-search-openai-javascript/pull/174
- https://github.com/Azure-Samples/contoso-real-estate/pull/429

**Comment by v-xuto** [comment]
@hemarina 12 new PRs were created today, please review.
- https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/pull/26
- https://github.com/Azure-Samples/fastapi-on-azure-functions/pull/29
- https://github.com/Azure-Samples/azure-search-openai-demo-java/pull/73
- https://github.com/Azure-Samples/bindings-dapr-csharp-cron-postgres/pull/8
- https://github.com/Azure-Samples/bindings-dapr-nodejs-cron-postgres/pull/8
- https://github.com/Azure-Samples/bindings-dapr-python-cron-postgres/pull/6
- https://github.com/Azure-Samples/pubsub-dapr-csharp-servicebus/pull/7
- https://github.com/Azure-Samples/pubsub-dapr-nodejs-servicebus/pull/18
- https://github.com/Azure-Samples/pubsub-dapr-python-servicebus/pull/7
- https://github.com/Azure-Samples/svc-invoke-dapr-csharp/pull/5
- https://github.com/Azure-Samples/svc-invoke-dapr-nodejs/pull/6
- https://github.com/Azure-Samples/svc-invoke-dapr-python/pull/6

**Comment by v-xuto** [comment]
@hemarina 8 new PRs were created today, please review.

- https://github.com/Azure-Samples/pubsub-dapr-aks-java/pull/6
- https://github.com/Azure/GPT-RAG/pull/95
- https://github.com/Azure-Samples/msdocs-django-postgresql-sample-app/pull/69
- https://github.com/Azure-Samples/azure-django-postgres-flexible-aca/pull/85
- https://github.com/Azure-Samples/msdocs-flask-postgresql-sample-app/pull/37
- https://github.com/Azure-Samples/react-component-toolkit-openai-demo/pull/8
- https://github.com/Azure/reliable-web-app-pattern-dotnet/pull/349
- https://github.com/Azure-Samples/ASA-Samples-Web-Application/pull/28

**Comment by v-xuto** [comment]
@hemarina Thanks for your quick review. 5 new PRs were created today, and added the owner of repos. Please review. For https://github.com/Azure-Samples/azure-django-postgres-flexible-aca/pull/85, we will create PR in repo https://github.com/kjaymiller/cookiecutter-relecloud.
- https://github.com/Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart/pull/122
- https://github.com/Azure-Samples/chatgpt-quickstart/pull/62
- https://github.com/Azure-Samples/spring-chatgpt-sample/pull/10
- https://github.com/Azure-Samples/spring-petclinic-java-mysql/pull/4
- https://github.com/Azure-Samples/apptemplate-wordpress-on-aca/pull/18

**Comment by v-xuto** [comment]
@hemarina 1 new PR was created today, please review.
- https://github.com/kjaymiller/cookiecutter-relecloud/pull/324

So far, we have created all PRs for the required templates. 
55 (All templates) = 37 PRs + 14 have supported templates + 2 have added templates + 2 no need templates

- 2 have added templates: In the Readme, they have their own corresponding metadata, but they are not displayed in the azure samples browser. We don't know what causes this.
https://github.com/Azure-Samples/todo-nodejs-mongo-aks
https://github.com/Azure-Samples/todo-python-mongo
- 2 no need templates：
https://github.com/Azure-Samples/azd-starter-bicep
https://github.com/Azure-Samples/azd-starter-terraform

**Comment by v-xuto** [comment]
@hemarina To fix invalid slugs, we have created 13 PRs, please review.

- https://github.com/Azure-Samples/function-python-ai-langchain/pull/7
- https://github.com/Azure-Samples/function-python-ai-textsummarize/pull/6
- https://github.com/Azure-Samples/azure-search-openai-demo-java/pull/75 
- https://github.com/Azure-Samples/pubsub-dapr-aks-java/pull/7
- https://github.com/Azure-Samples/msdocs-django-postgresql-sample-app/pull/73
- https://github.com/Azure-Samples/msdocs-flask-postgresql-sample-app/pull/39
- https://github.com/Azure-Samples/openai-chat-app-quickstart/pull/68
- https://github.com/Azure-Samples/apptemplate-wordpress-on-aca/pull/19
- https://github.com/Azure-Samples/spring-petclinic-java-mysql/pull/5
- https://github.com/Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart/pull/126
- https://github.com/Azure-Samples/pubsub-dapr-python-servicebus/pull/8
- https://github.com/Azure-Samples/pubsub-dapr-nodejs-servicebus/pull/19
- https://github.com/Azure-Samples/pubsub-dapr-csharp-servicebus/pull/8

**Comment by v-xuto** [comment]
@hemarina To fix invalid slugs, 2 new PRs were created today, please review.

- https://github.com/Azure/GPT-RAG/pull/99
- https://github.com/Azure/reliable-web-app-pattern-dotnet/pull/352

**Comment by v-xuto** [comment]
@hemarina In [Microsoft authored templates](https://azure.github.io/awesome-azd/?tags=msft), there are two new repos. So, 2 PRs for adding metadata are ready, please review.

- https://github.com/Azure-Samples/aks-store-demo/pull/107
- https://github.com/Azure-Samples/openai-aca-lb/pull/4

**Comment by zedy-wj** [comment]
@hemarina - We have filed one more PR to fix issue [#760](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/760).

- https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/764

**Comment by v-xuto** [comment]
@hemarina 9 new PRs were created today, please review.
- https://github.com/dotnet/ai-samples/pull/63
- https://github.com/Azure-Samples/openai-apim-lb/pull/19
- https://github.com/microsoft/aoai-logging-with-apim/pull/21
- https://github.com/Azure-Samples/azure-sql-db-session-recommender-v2/pull/8
- https://github.com/Azure-Samples/agent-openai-python-prompty/pull/87
- https://github.com/Azure-Samples/azure-appconfig-aks/pull/7
- https://github.com/Azure-Samples/agent-python-openai-prompty-langchain/pull/27
- https://github.com/Azure-Samples/agent-openai-python-prompty-langchain-pinecone/pull/33
- https://github.com/Azure-Samples/openai-chat-app-quickstart/pull/129

**Comment by v-xuto** [comment]
@hemarina 3 new PRs were created today, please review.

- https://github.com/Azure/APICenter-Analyzer/pull/19
- https://github.com/Azure/APICenter-Portal-Starter/pull/21
- https://github.com/Azure-Samples/APICenter-Reference/pull/33

**Comment by justinyoo** [comment]
@rajeshkamal5050 I've got a question around this frontmatter metadata. Can this frontmatter be wrapped with `<!-- ... -->`?

For example, here's the APICenter-Reference:

```
---
page_type: sample
languages:
- azdeveloper
- javascript
- csharp
- powershell
- bash
- html
- bicep
products:
- azure
- azure-api-center
- azure-api-management
- azure-app-service
- azure-event-grid
- azure-logic-apps
- static-web-apps
urlFragment: APICenter-Reference
name: API Center Reference
description: Let developer experiences how to use API Center (APIC) and seamless integration with API Management (APIM), as well as inner-loop development velocity increase.
---
```

Instead of doing that, I wonder if it's possible to put like:

```
<!--
---
page_type: sample
languages:
- azdeveloper
- javascript
- csharp
- powershell
- bash
- html
- bicep
products:
- azure
- azure-api-center
- azure-api-management
- azure-app-service
- azure-event-grid
- azure-logic-apps
- static-web-apps
urlFragment: APICenter-Reference
name: API Center Reference
description: Let developer experiences how to use API Center (APIC) and seamless integration with API Management (APIM), as well as inner-loop development velocity increase.
---
-->
```

By doing so, this frontmatter is not visible to the reader, but machine still can read it?

**Comment by v-xuto** [comment]
@hemarina About above [comments](https://github.com/Azure/awesome-azd/issues/281#issuecomment-2169009513), any ideas? Can we create a new `docs/README.md` file in repos and add metadata to the `README.md` under docs, such as: https://github.com/azure-samples/azure-search-openai-javascript/tree/main/docs.
