### ISSUE TITLE
Add tags/copy button track for adobe support

### ISSUE THREAD

**Issue by hemarina** [Azure/awesome-azd#357]
Currently adobe is not tracking every button (filter tags, copy button) click on the site.

**Comment by kristenwomack** [comment]
Thank you, do you know what the effort would be to enable click tracking on:

- the template name on the main page that opens the panel with more information
- the copy/paste buttons for the command on each template repo listed on the main page
- the copy/paste command on the quick use and VS Code commands on the side panel (that opens when you select the template name

**Comment by kristenwomack** [comment]
Sounds good, thank you Marina! Is it possible to track the card panel elements? Maybe a future item.
