### ISSUE TITLE
[Submit Template] Azure SQL + Prisma

### ISSUE THREAD

**Issue by glaucia86** [Azure/awesome-azd#43]
## New azd-template Submission

Fill in the sections below to populate a new Gallery carry for your template. An example of a valid template object is given at the end for reference. **All fields are mandatory unless explicitly identified as optional**

### 1. Title 
Full Stack Application with Azure SQL & Prisma

## 2. Description
A real study case application how to apply Node.Js with:

* Azure SQL
* Prisma
* Vue.Js
* Azure Functions
* Azure Static Web Apps
* Azure Dev CLI

## 3. Author Profile

**[GitHub Repository Link](https://github.com/glaucia86/azure-sql-prisma-vue)**
**[Author - Glaucia Lemos](https://github.com/glaucia86)**

## 4. Author Name
Glaucia Lemos

## 5. Template Repo
_The GitHub repo containing the template being contributed - must be a valid, complete template_

## 6. Standard Tags

vuejs, azure-functions, azure-static-web-apps, azure-sql, nodejs, javascript, azure, prisma, github-actions, dev-container

## 7. Additional Tags (`optional`)
_Don't see a relevant standard tag for your template? Request these tags be added, and then used for your template. These could be new languages, services, or application domains_.

## 8. Architecture Diagram or Application Screenshot

**[HERE](https://github.com/glaucia86/azure-sql-prisma-vue/tree/main/docs)**

---

## Example Of Valid Template

```
  {
    title: 'Full Stack Application with Azure SQL & Prisma',
    description: 'A Full Stack Application how you can build a CRUD application using Azure SQL, Prisma, Azure Functions and with a deployment of this application with Azure Static Web Apps integrated with GitHub Actions. ',
      preview: ``,
    website: 'https://github.com/glaucia86',
    author: 'Glaucia Lemos',
    source: 'https://github.com/glaucia86/azure-sql-prisma-vue',
    tags: ['vuejs','azure-functions','javascript','nodejs','azure-sql','azure-static-web-apps','prisma','dev-container'],
  },
```
---

## Next Steps

Once submitted the issue will be reviewed - we plan to do reviews on a rolling basis at regular intervals. The process will involve checking that template information is complete, and the template is valid. 
 * If we have questions or enhancements, we will add comments in issue thread (**issue stays open**)
 * If the contribution is approved, we'll update the gallery directly (**issue will then be closed**)

**Comment by jongio** [comment]
1. Please have a look at the all new bicep module structure and get the /core modules in the project and then follow that same structure as much as possible.  
2. In azure.yaml, provider section is optional. You can remove it.
3. Please update azure.yaml to include the full app.  

I think it will be best if you open a PR against your repo so I can provide feedback in the form of PR comments.

**Comment by jongio** [comment]
Since you are using SQL server, you may want to reach out to @madebygps who is wrapping up a similar template.  You'll want to follow that same pattern for getting and setting passwords (if you can).

https://github.com/Azure/azure-dev/pull/551

**Comment by glaucia86** [comment]
> 1. Please have a look at the all new bicep module structure and get the /core modules in the project and then follow that same structure as much as possible.
> 2. In azure.yaml, provider section is optional. You can remove it.
> 3. Please update azure.yaml to include the full app.
> 
> I think it will be best if you open a PR against your repo so I can provide feedback in the form of PR comments.

Hi, @jongio. I confess that I have some difficult to create these files. Once I'm still learning it and I think so difficult to create. Who created for me these infra was @manekinekko. If you could update it, I really appreciated it.

**Comment by manekinekko** [comment]
I am working on this issue @glaucia86 👍

**Comment by manekinekko** [comment]
@jongio while working on updating the PR for Glaucia, I had a few comments and questions: 

> Please have a look at the all new bicep module structure and get the /core modules in the project and then follow that same structure as much as possible.

Are all those core modules required for this template? The template doesn't need all of those services. Is azd parsing this exact folder structure? Or can it be flexible?

> In azure.yaml, provider section is optional. You can remove it.

Done.

> You'll want to follow that same pattern for getting and setting passwords (if you can).

The app in this template is not using KeyVault. This is why we haven't provisioned that resource. Also, I was checking PR #551 and noted this function[ `secretOrRandomPassword`](https://github.com/Azure/azure-dev/pull/551/files#diff-d0c6d6eabd90e066194a53ea66352e3f2046e394f974e0adb1b617b6214f0a0eR15). Where is this function defined?

> Add azd to the devcontainer - see https://github.com/Azure/azure-dev/tree/main/templates/common/.devcontainer for a bunch of examples

Done.

> Please update azure.yaml to include the full app.

The template is meant to be deployed to SWA. Both client and API. This is currently not possible using `azd deploy` (see https://github.com/Azure/azure-dev/issues/837 )

> Add azd up and azd install steps to the readme.

It's already there (at the bottom under > Project: db). Do you need to be moved elsewhere?

**Comment by jongio** [comment]
Okay, I didn't see that as it is a collapsed section.

1. Please move to using `azd env set` commands for setting env vars instead of asking them to create a .env in the api folder.
2. You don't need all of what is in /core.  But the structure should be adopted in templates coming from MS.  You can remove what you don't need.
3. secretOrRandomPassword https://github.com/Azure/azure-dev/blob/8bb8e2d992b7fb2878d2be489adaedac5d567e93/cli/azd/pkg/cmdsubst/secretOrRandomPassword.go
4. Are you using the SWA config file in this app to deploy the API?

**Comment by manekinekko** [comment]
> Please move to using azd env set commands for setting env vars instead of asking them to create a .env in the api folder.

@glaucia86 are you OK with this change? Would this affect the structure of your videos?

> You don't need all of what is in /core. But the structure should be adopted in templates coming from MS. You can remove what you don't need.

Gotcha!

> Are you using the SWA config file in this app to deploy the API?

Yes. Because of this https://github.com/Azure/azure-dev/issues/837

**Comment by glaucia86** [comment]
> > Please move to using azd env set commands for setting env vars instead of asking them to create a .env in the api folder.
> 
> @glaucia86 are you OK with this change? Would this affect the structure of your videos?
> 
> > You don't need all of what is in /core. But the structure should be adopted in templates coming from MS. You can remove what you don't need.
> 
> Gotcha!
> 
> > Are you using the SWA config file in this app to deploy the API?
> 
> Yes. Because of this [Azure/azure-dev#837](https://github.com/Azure/azure-dev/issues/837)

Sorry for my delay here. No problem @manekinekko. Later I can create a article or another video with these new changes.

**Comment by jongio** [comment]
/core has been updated. please have a look at what is in main

Also LMK if you want to work together on this.

**Comment by jongio** [comment]
@glaucia86 - Would you like to work on getting this updated/added?

**Comment by glaucia86** [comment]
> @glaucia86 - Would you like to work on getting this updated/added?
Hi, @jongio! If you could help me, I will really appreciate it!

**Comment by rajeshkamal5050** [comment]
@jongio can you help @glaucia86 in moving to core bicep modules?

**Comment by manekinekko** [comment]
@rajeshkamal5050 @jongio fwiw, I've started doing some migration work in my [PR here](https://github.com/glaucia86/azure-sql-prisma-vue/pull/12) for @glaucia86. Feel free to grab that PR so that you don't have to start from scratch.

**Comment by glaucia86** [comment]
Thank you, @manekinekko. I really appreciate that.

**Comment by rajeshkamal5050** [comment]
@glaucia86 any updates on the template?
