### ISSUE TITLE
Rename Build 2024 filter tag to AI Collection

### ISSUE THREAD

**Issue by kristenwomack** [Azure/awesome-azd#431]
We will use our aka.ms/ai-apps link to point to a collection of AI templates here in /awesome-azd and update the filter tag `AI Collection`

- [x] RENAME `Build 2024 Collection` to `AI Collection`
- [x] Add new tag for 'AI Collection'
- [x] Update templates for AI Gallery with tag '`AI Collection`
- [x] Remove `Build 2024 Collection` tag option
- [x] Remove `Build 2024 Collection` tag 
- [x] Add the new tage to the collection of 18 templates (cc @gkulin)
- [x] Repoint the AI aka link
 
![image](https://github.com/user-attachments/assets/3f8669ee-c1b4-40d1-9bc3-8f51324efb03)

**Comment by gkulin** [comment]
aka link updated! https://aka.ms/ai-apps

**Comment by kristenwomack** [comment]
Thank you! All looks great.
