### ISSUE TITLE
[New azd-template] A Blazor Todo App with Dapr and PostgreSQL

### ISSUE THREAD

**Issue by briandenicola** [Azure/awesome-azd#49]
{
    title: 'ToDo Application - Blazor C# PostgreSQL',
    description:
      'A simple Blazor ToDo application, C# for the API, Azure PostgreSQL DB SQL API for storage and Azure Container Apps with Dapr for runtime',
    website: 'https://github.com/briandenicola',
    author: 'Brian Denicola',
    source: 'https://github.com/briandenicola/devcontainer-demo-with-azure-developer-cli',
    tags: ['devcontainers','csharp','postgresql','containerapp','dapr','blazor','keyvault','codespaces'],
  },

**Comment by jongio** [comment]
I'm getting an exception when I run azd up on this template.  I will continue to investigate it tomorrow.

**Comment by jongio** [comment]
This is an interesting case because of the blazor (wasm) limitation of not having access to env vars.  I'm investigating ways that we can automate the setup here.  Related to: https://github.com/Azure/azure-dev/issues/958

**Comment by jongio** [comment]
@briandenicola - Did this work for you doing azd up?

**Comment by rajeshkamal5050** [comment]
> @briandenicola - Did this work for you doing azd up?

Hi @briandenicola any updates on this?

**Comment by jongio** [comment]
@briandenicola Do you want to try the new hooks feature to update the URI you need in blazor config? https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-extensibility
