### ISSUE TITLE
3 Templates with Missing Bicep/Terraform Tags.

### ISSUE THREAD

**Issue by Austinauth** [Azure/awesome-azd#60]
**Describe the bug**

3 Templates are currently missing an _Infrastructure as Code_ (Bicep or Terraform) tag. Since every template must include assets written in Bicep or Terraform, they should all probably indicate which one they use. 

- PyCon Workshop - Django On Azure
- Rock, Paper, Orleans (RPO) - Distributed .NET
- ToDo Application - React C# CosmosDB SQL

**Comment by nitya** [comment]
I will add these in today since I have a couple of other updates and close issue then /cc @savannahostrowski 
Also good feedback for the templates used in terms of requiring people to add a mandatory Infra-as-Code tag.

**Comment by Austinauth** [comment]
@nitya Awesome, thanks for looking into it!
