### ISSUE TITLE
Include the init command for each template

### ISSUE THREAD

**Issue by tonybaloney** [Azure/awesome-azd#71]
Once you've seen a template you like, it's a few steps to click on it, copy the git URL and then put it into the cli to initialise a project.

It would be handy to have the snippet:

`azd init --template <url>` in the templates gallery within the pane for each template and a copy button so I can quickly grab it.

Thanks,

**Comment by jongio** [comment]
@Austinauth

**Comment by rajeshkamal5050** [comment]
We have already addressed this as part of awesome-azd template cards which you can just copy and use.

**Comment by Austinauth** [comment]
As Rajesh mentioned, this functionality will exist when the updated card designs are implemented.

![image](https://user-images.githubusercontent.com/6994218/213800964-25ccd10a-0b17-4e71-b88b-6a46e9d627b6.png)
