### ISSUE TITLE
[New azd-template] todo-java-postgresql-aca-terraform

### ISSUE THREAD

**Issue by fangjian0423** [Azure/awesome-azd#77]
## New azd-template Submission

Fill in the sections below to populate a new Gallery carry for your template. An example of a valid template object is given at the end for reference. **All fields are mandatory unless explicitly identified as optional**

### 1. Title 
_Short template name that will be used in card title on gallery_

**ToDo Application - Java PostgreSQL Container Apps Terraform**

## 2. Description
_1-2 sentence description of the architecture or solution that is defined by the template_

**A complete ToDo application that includes everything you need to build, deploy, and monitor an Azure solution. This application uses the Azure Developer CLI (azd) to get you up and running on Azure quickly, React.js for the Web application, Java for the API, Azure Database for PostgreSQL - Flexible Server for storage, and Azure Monitor for monitoring and logging.**

## 3. Author Profile
_A link to the contributor's GitHub profile (ideal) or other profile link (for identification_.

**https://github.com/fangjian0423**

## 4. Author Name
_The name to be shown in the grey button on the card - will be linked profile website above_.

**Jimmy Fang**

## 5. Template Repo
_The GitHub repo containing the template being contributed - must be a valid, complete template_

**https://github.com/fangjian0423/todo-java-postgresql-aca-terraform**

## 6. Link to PR where you made your repo `azd` compatible
_To allow us to provide feedback on your template, please include a link to the PR where you added `azd` compatibility_

It's a new project. Could you pls create a new issue if you want to provide feedback.

## 7. Standard Tags
_One or more tags representing the template. Look at the currently available tags on the Gallery page and pick at least 1 tag for programming language used, and 1 tag for Azure services integrated_

**`java`, `containerapps`, `postgresql`, `monitor`, `passwordless`, `application insights`, `terraform`** 

## 7. Additional Tags (`optional`)
_Don't see a relevant standard tag for your template? Request these tags be added, and then used for your template. These could be new languages, services, or application domains_.

**`spring`**

## 8. Architecture Diagram or Application Screenshot
_Used as default image for template card - must be representative of solution being enabled. Submit image by adding it as file upload to this issue_

![image](https://github.com/fangjian0423/todo-java-postgresql-aca-terraform/blob/main/assets/resources.png?raw=true)

---

## Example Of Valid Template

```
{
  title: 'ToDo Application - Java PostgreSQL Container Apps Terraform',
  description:
    'Complete React.js ToDo application, Java for the API, Azure Database for PostgreSQL - Flexible Server for storage, and Azure Monitor for monitoring and logging.',
    preview: `todo-java-postgresql-aca-terraform.png`,
  website: 'https://github.com/fangjian0423',
  author: 'Jimmy Fang',
  source: 'https://github.com/fangjian0423/todo-java-postgresql-aca-terraform',
  tags: ['java', 'containerapps', 'postgresql', 'monitor', 'passwordless', 'application insights', 'terraform']
}
```
---

## Next Steps

Once submitted the issue will be reviewed - we plan to do reviews on a rolling basis at regular intervals. The process will involve checking that template information is complete, and the template is valid. 
 * If we have questions or enhancements, we will add comments in issue thread (**issue stays open**)
 * If the contribution is approved, we'll update the gallery directly (**issue will then be closed**)

**Comment by rajeshkamal5050** [comment]
@v-xuto can you do a dry on this template and update here for any issues/feedback?

**Comment by v-xuto** [comment]
@fangjian0423  We have tested the template `todo-java-postgresql-aca-terraform`, we filed one issue (https://github.com/fangjian0423/todo-java-postgresql-aca-terraform/issues/1), please review it.

Please help to add a hint to the README about `PostgreSQL`, such as `make sure psql command is available in your terminal`.

Besides, when executing the command `azd up` is executed, many of the available locations introduced in the README, our subscription `Azure SDK Developer Playground` is not allowed to provision in `Brazil South, Canada Central, Central US, East Asia, Eastus2, Germany West Central, Japan East, Korea Central, North Central US, North Europe, UK South, West US` for `PostGreSQL flexible server`, so we can't help to verify the avaliable locations.

**Comment by v-xuto** [comment]
@fangjian0423 Please add relevant hints in `README`: Before executing `azd pipeline config`, need to execute `azd down` and enable remote state according to the [document](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/use-terraform-for-azd#azd-pipeline-config-for-terraform).

**Comment by rajeshkamal5050** [comment]
@jongio @weikanglim @wbreza please review.

**Comment by v-xuto** [comment]
@jongio We have finished testing this template, and there is only a same issue(https://github.com/fangjian0423/todo-java-postgresql-terraform/issues/3) with template `todo-java-postgresql-terraform` now. For this issue, we did not file it in this template.

**Comment by wbreza** [comment]
Are we considering adding this into azure/azure-dev repo to generate along side our official repos? If so we should open a PR with these changes.

**Comment by rajeshkamal5050** [comment]
@jongio @savannahostrowski is it okay for this to be served from https://github.com/fangjian0423/todo-java-postgresql-aca-terraform?

**Comment by rajeshkamal5050** [comment]
Closing this in favor of a new ACA template will be added as such - https://github.com/Azure/azure-dev/pull/1792
