### ISSUE TITLE
[New azd-template] apptemplate-wordpress-on-ACA

### ISSUE THREAD

**Issue by kpantos** [Azure/awesome-azd#93]
## New azd-template Submission
Fill in the sections below to populate a new gallery card for your template. **All fields are mandatory unless explicitly identified as optional**

## 1. Description
In this application template, you'll learn how to and will be able to easily, quickly create and deploy your first scalable and secure [WordPress](https://www.wordpress.org/) site to Azure, leveraging [Azure Container Apps](https://learn.microsoft.com/en-us/azure/container-apps/overview) with [Azure Database for MariaDb](https://learn.microsoft.com/en-us/azure/mariadb/overview).

## 2. Author Information
**Name:** Konstantinos Pantos

**Link:** [kpantos](https://github.com/kpantos)

## 3. Template Repo
[https://github.com/Azure-Samples/apptemplate-wordpress-on-ACA](https://github.com/Azure-Samples/apptemplate-wordpress-on-ACA)

## 4. Link to PR where you made your repo `azd` compatible
No PR, initially built to be azd compatible

## 5. Tags
**Standard:** php, Azure Container Apps, Azure Application Gateway, Azure MariaDB, Bicep

**Additional:** WordPress

## 6. Architecture Diagram or Application Screenshot
![WordPress on ACA](https://github.com/Azure-Samples/apptemplate-wordpress-on-ACA/raw/main/assets/azure.png)

## 7. Related Issues (optional)
_Is this a template that was requested in a separate issue? If so, please tag the related issue here._
---
## Next Steps
Once submitted, the issue will be reviewed - we plan to do reviews on a rolling basis at regular intervals. The process will include verifying all information required for the template gallery is provided and the template works (i.e., successfully deploys to Azure with `azd up`). 
 * If we have questions or enhancements, we will add comments in issue thread (**issue stays open**)
 * If the contribution is approved, we'll update the gallery directly (**issue will then be closed**)

**Comment by rajeshkamal5050** [comment]
@v-xuto please please do a dry run of the template and provide feedback, if any.

@jongio please review.

**Comment by jongio** [comment]
I gave feedback to @puicchan today, I think she was going to integrate it.

**Comment by puicchan** [comment]
I am looking at it.

**Comment by jongio** [comment]
@kpantos - can you please make the repo name all lowercase to be consistent with other templates?  Not required, but nice

**Comment by kpantos** [comment]
@jongio - Unfortunately, I don't own the repository so I can't change the name. I have forwarded this to Aarthi to see if she can help.

**Comment by puicchan** [comment]
@kpantos, I have created a few issues in azure-samples/apptemplate-wordpress-aca. Ping me if you have questions.

**Comment by v-xuto** [comment]
When we were testing this template, we encountered an old issue (https://github.com/Azure/azure-dev/issues/1289#issuecomment-1434395128).
And we will continue testing after it is resolved.

**Comment by kpantos** [comment]
@v-xuto can you please paste the logs of the issue you mentioned? 
Also, can you please add the version of Bicep you're using?

**Comment by jongio** [comment]
> @jongio - Unfortunately, I don't own the repository so I can't change the name. I have forwarded this to Aarthi to see if she can help.

I renamed it just now.

**Comment by kpantos** [comment]
Thanks @jongio

**Comment by v-xuto** [comment]
> @v-xuto can you please paste the logs of the issue you mentioned? Also, can you please add the version of Bicep you're using?

- **Bicep version:**`Bicep CLI version 0.14.46 (ef2ceb1a0e)`
- **Logs of the issue:**
```
PS D:\code\AzdTemplate\apptemplate-wordpress-on-ACA> azd provision

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time

  |====== | Creating a deployment planpanic: unexpected bicep type: 'securestring'

goroutine 36 [running]:
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).mapBicepTypeToInterfaceType(0x14cb240?, {0xc00002ece0?, 0xc})
        D:/a/_work/1/s/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:747 +0x228
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).ensureParameters(0xc000536000, {0x1772f68, 0xc0003195c0}, 0xc0002afe10?, {{0xc0005860c0, 0x5b}, {0xc00002e780, 0x7}, 0xc0000ae300, 0xc0000ae540}, ...)
        D:/a/_work/1/s/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:949 +0x695
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).Plan.func1(0xc000319ad0)
        D:/a/_work/1/s/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:145 +0x3cd
github.com/azure/azure-dev/cli/azd/pkg/async.(*InteractiveTaskWithProgress[...]).Run.func1()
        D:/a/_work/1/s/cli/azd/pkg/async/task.go:191 +0x1a8
created by github.com/azure/azure-dev/cli/azd/pkg/async.(*InteractiveTaskWithProgress[...]).Run
        D:/a/_work/1/s/cli/azd/pkg/async/task.go:186 +0x1cb
```

**Comment by kpantos** [comment]
@v-xuto can you please update your bicep tooling to the latest one and try again?
I'm running the `Bicep CLI version 0.14.85 (f4a4d485ba)`  version and don't have the specific issue.

**Comment by v-xuto** [comment]
@kpantos We have updated the Bicep CLI version to `0.14.85 (f4a4d485ba)`, but this issue can still be reproduced.
Are we missing some configuration?

![image](https://user-images.githubusercontent.com/57166602/222322019-1f4040db-e987-4159-86e9-587203e9c3d1.png)

**Comment by puicchan** [comment]
Successfully `azd provision` this template to "east us 2". An existing WordPress image is being deployed via Bicep to ACA so not necessary to run `azd deploy`. 

@kpantos - I have created a PR: https://github.com/Azure-Samples/apptemplate-wordpress-on-aca/pull/8 and also logged a new issue. Pls take a look.

**Comment by v-xuto** [comment]
@kpantos This issue (https://github.com/Azure/azure-dev/issues/1289#issuecomment-1447916718) has been resolved. But, when we continued to test, we encountered a new issue (https://github.com/Azure-Samples/apptemplate-wordpress-on-aca/issues/11) and filed it, please help to check and solve it. Thanks.

**Comment by rajeshkamal5050** [comment]
@kpantos when you get a chance. Please look into the reported issue,
- https://github.com/Azure-Samples/apptemplate-wordpress-on-aca/issues/11

**Comment by jongio** [comment]
🚢

**Comment by rajeshkamal5050** [comment]
@v-xuto reported issue above is fixed. Can we run the latest?

**Comment by v-xuto** [comment]
> @v-xuto reported issue above is fixed. Can we run the latest?

@rajeshkamal5050 We've finished testing based on the latest, without any issues.

**Comment by kpantos** [comment]
@rajeshkamal5050 is the template published in the awesome site yet? 
Is there something pending?

**Comment by rajeshkamal5050** [comment]
@kpantos looks like the approvals and testing were good. 

Can you can create a PR following [this](https://github.com/Azure/awesome-azd/blob/main/.github/PULL_REQUEST_TEMPLATE.md#if-you-are-submitting-a-new-azd-template-to-the-gallery) to get the approved template added to the gallery.

Ref PR's:
- https://github.com/Azure/awesome-azd/pull/125
- https://github.com/Azure/awesome-azd/pull/121

**Comment by gkulin** [comment]
completed via #140
