### ISSUE TITLE
[New azd-template] Flask Chart API on ACA + CDN

### ISSUE THREAD

**Issue by pamelafox** [Azure/awesome-azd#98]
## New azd-template Submission
Fill in the sections below to populate a new gallery card for your template. **All fields are mandatory unless explicitly identified as optional**

## 1. Description
_1-2 sentence description of the architecture or solution that is defined by the template. If this is a requested template, please tag the GitHub issue containing the request._

A Charts API that renders PNGs of bar and pie charts, built with Python Flask, APIFlask, and matplotlib. Can be run locally with Docker and then deployed to Azure Container Apps with an Azure CDN in front.

## 2. Author Information
**Name:** pamelafox

**Link:** [_To the author's GitHub profile (ideal) or other profile link_](https://github.com/pamelafox)

## 3. Template Repo
_The GitHub repo containing the template being contributed-- must be a valid, complete template_

https://github.com/pamelafox/flask-charts-api-container-app

## 4. Link to PR where you made your repo `azd` compatible
_To allow us to provide feedback on your template, please include a link to the PR where you added `azd` compatibility_

There's not one particular PR, but you can check azure.yaml, the infra/ folder, and .github/workflows. This infra is the same as my other Flask ACA + CDN submission, but I refactored the CDN to be core/ modules and renamed 'web' module to 'api'.

## 5. Tags
**Standard:** _One or more tags representing the template. Look at the currently available tags on the [Gallery page](https://azure.github.io/awesome-azd/). Provide **at least 1 tag** for programming language used and **at least 1 tag for Azure services integrated**. Also tag the **IaC provider** (Bicep or Terraform)_

Python, Flask, Web Apps, Azure Container Apps

**Additional:** _Don't see a relevant tag for your template? Suggest tags to be added and used for your template. These could be new languages, services, or application domains_.

Azure CDN

## 6. Architecture Diagram or Application Screenshot
_Used as display image for gallery card-- should include all services and their connections. [Example](https://github.com/Azure-Samples/todo-csharp-sql/blob/main/assets/resources.png)_

![readme_diagram](https://user-images.githubusercontent.com/297042/221662732-9bd3f546-fb10-46bb-ac26-6c3a959390f6.png)

## 7. Related Issues (optional)
_Is this a template that was requested in a separate issue? If so, please tag the related issue here._

---
## Next Steps
Once submitted, the issue will be reviewed - we plan to do reviews on a rolling basis at regular intervals. The process will include verifying all information required for the template gallery is provided and the template works (i.e., successfully deploys to Azure with `azd up`). 
 * If we have questions or enhancements, we will add comments in issue thread (**issue stays open**)
 * If the contribution is approved, we'll update the gallery directly (**issue will then be closed**)

**Comment by rajeshkamal5050** [comment]
@v-xuto can you do a dry-run on this template and update here for any issues/feedback?

**Comment by v-xuto** [comment]
@pamelafox  We have finished testing this template. We found an issue in README and filed the issue, please review and update.
Issue link: https://github.com/pamelafox/flask-charts-api-container-app/issues/6

**Comment by pamelafox** [comment]
Fixed, thanks!

**Comment by v-xuto** [comment]
@rajeshkamal5050 We've run this template without any issues.

**Comment by rajeshkamal5050** [comment]
@jongio kindly review it when you get a chance.

@hemarina please add it to gallery post review and approval by Jon.

**Comment by jongio** [comment]
:shipit:
